[theme]
# اللون الرئيسي للأزرار والعناوين
primaryColor = "#0A66C2"

# خلفية الصفحة (أزرق فاتح)
backgroundColor = "#EAF4FF"

# خلفية الشريط الجانبي (أزرق أغمق قليلاً)
secondaryBackgroundColor = "#CFE3FF"

# لون النصوص والعناوين
textColor = "#0F172A"

# نوع الخط الافتراضي
font = "sans serif"
